name: fastvideoplayer
description: This is an intuitive video player with precache support for FastAd. It reduces the boilerplate code required to use a video player.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.6
  flutter_hooks: ^0.20.5
  flutter_cache_manager: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
